# Generated by Django 4.0.1 on 2022-01-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id_commissions', models.BigAutoField(primary_key=True, serialize=False)),
                ('commissions_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id_seller', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('commissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.commissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.user')),
            ],
        ),
        migrations.AddField(
            model_name='commissions',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.seller'),
        ),
    ]
