# Generated by Django 4.0.1 on 2022-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
