# Generated by Django 4.0.1 on 2022-01-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_commissions_commissions_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='main_image',
            field=models.ImageField(default='commissions/images/commissions_images/default.jpg', upload_to='commissions/images/commissions_images/'),
        ),
    ]
