# Generated by Django 4.0.1 on 2022-01-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_remove_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(default='HI', on_delete=django.db.models.deletion.CASCADE, to='commissions.user'),
            preserve_default=False,
        ),
    ]
