# Generated by Django 4.0.1 on 2022-01-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissions',
            name='seller',
        ),
    ]
