# Generated by Django 4.0.1 on 2022-01-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_remove_commissions_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissions',
            name='seller',
            field=models.ForeignKey(default='AAA', on_delete=django.db.models.deletion.CASCADE, to='commissions.seller'),
            preserve_default=False,
        ),
    ]
