# Generated by Django 4.0.1 on 2022-01-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_rename_seller_commissions_id_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissions',
            old_name='id_seller',
            new_name='seller',
        ),
    ]
